close all;
clear all;
clc;
I1=imread('C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\0189.bmp');
I=medfilt2(I1);
%imwrite(I,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\中值滤波一.bmp');
h1=[-1 0 1;-2 0 2;-1 0 1];
h2=[1 2 1;0 0 0;-1 -2 -1];
% h3=[0 1 2;-1 0 1;-2 -1 0];
% h4=[1 1 0;2 0 -1;0 -1 -2];
J1=imfilter(I,h1);
J2=imfilter(I,h2);
% J3=imfilter(I,h3);
% J4=imfilter(I,h4);
 J=4*J1+1.5*J2;
 %imwrite(J,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\SOBEL1.bmp');
J0=medfilt2(J,[5,5]);
imwrite(J0,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\滤波1.bmp');
figure,imshow(J0);title('第一幅边缘检测滤波之后');
f=im2double(J0);
se=strel('disk',10);
ft=imtophat(f,se);
Thr=graythresh(ft);
lt=imbinarize(ft,Thr);
lt=imclose(lt,se);
%figure,imshow(lt);
at=bwareaopen(lt,300);
figure,imshow(at);title('第一幅图阈值');
imwrite(at,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\飞溅阈值.bmp');
I1=imread('C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\0190.bmp');
I=medfilt2(I1);
%imwrite(I,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\中值滤波二.bmp');
h1=[-1 0 1;-2 0 2;-1 0 1];
h2=[1 2 1;0 0 0;-1 -2 -1];
% h3=[0 1 2;-1 0 1;-2 -1 0];
% h4=[1 1 0;2 0 -1;0 -1 -2];
J1=imfilter(I,h1);
J2=imfilter(I,h2);
% J3=imfilter(I,h3);
% J4=imfilter(I,h4);
J=4*J1+1.5*J2;
%imwrite(J,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\SOBEL2.bmp');
J0=medfilt2(J,[5,5]);
imwrite(J0,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\滤波2.bmp');
figure,imshow(J0),title('第二幅边缘检测滤波之后'),impixelinfo;
f=im2double(J0);
se=strel('disk',10);
ft=imtophat(f,se);
Thr=graythresh(ft);
lt=imbinarize(ft,Thr);
lt=imclose(lt,se);
bt=bwareaopen(lt,300);
figure,imshow(bt);title('第二幅图阈值');
imwrite(bt,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\下一张阈值.bmp');
K=(at)&(bt);
figure,imshow(K);
%imwrite(K,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\与运算阈值.bmp');
K=bwareaopen(K,300);
imwrite(K,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\与运算XIAOC.bmp');
K=bwmorph(K,'thin',Inf);

figure,imshow(K);title('与运算');
%imwrite(K,'C:\Users\xiaohao\Desktop\图像处理技术\焊缝照片（原始）\与运算细化.bmp');

